[application]
mode = "Dev"

[blockstore]

[consensus]
address = "/ip4/0.0.0.0/udp/18000"
mempool_address = "/ip4/0.0.0.0/udp/18002"
store_path = "~/.fleek/mock/node1/narwhal_store"
worker_address = "/ip4/0.0.0.0/udp/18001"

[handshake]
listen_addr = "0.0.0.0:6970"

[indexer]

[pod]

[rep-collector]
reporter_buffer_size = 50

[rpc]
addr = "127.0.0.1"
port = 4070

[signer]
network_key_path = "keystore/consensus/network.key"
node_key_path = "keystore/consensus/primary.key"
