[application]
mode = "Dev"

[blockstore]

[consensus]
address = "/ip4/0.0.0.0/udp/38000"
mempool_address = "/ip4/0.0.0.0/udp/38002"
store_path = "data/node3/narwhal_store"
worker_address = "/ip4/0.0.0.0/udp/38001"

[handshake]
listen_addr = "0.0.0.0:6972"

[indexer]

[pod]

[rep-collector]
reporter_buffer_size = 50

[rpc]
addr = "127.0.0.1"
port = 4072

[signer]
network_key_path = "keystore/consensus/network.key"
node_key_path = "keystore/consensus/primary.key"
